### ISSUE TITLE
Definir um nome para o nosso Hackathon

### ISSUE THREAD

**Issue by woliveiras** [training-center/hackathon#1]
Com base na reunião que rolou depois da idealização do Hackathon, já temos tudo definido e precisamos agora somente tocar o projeto.

O primeiro ponto a se levantar para resolução em conjunto com a comunidade:

**Como vai se chamar nosso evento?**

Related to: [/sobre - issue 23](https://github.com/training-center/sobre/issues/23#issuecomment-323557391)

**Comment by woliveiras** [comment]
Algumas sugestões já enviadas pelo @khaosdoctor e @danilosilvadev:

* HackaCenter2017
* HackaTC2017

**Comment by hjdesigner** [comment]
HackaCenter2017 +1

**Comment by adeonir** [comment]
HackaCenter2017 +1

Depois de definidos alguns nomes, pode-se fazer um typeform pra a votação.

**Comment by danilosilvadev** [comment]
Vou adicionar mais uma opção que é mais divertida q os nomes acima só q é inusitado e tribal kk: **Hackahacka2017**

**Comment by khaosdoctor** [comment]
Realmente HackaTC2017 não ficou muito bom, voto no HackaCenter

**Comment by ericmadureira** [comment]
Também gostei do HackaCenter!

**Comment by khaosdoctor** [comment]
Fecharei o tópico porque definimos já como HackaCenter :D
