### ISSUE TITLE
Critérios para escolha dos mentores

### ISSUE THREAD

**Issue by danilosilvadev** [training-center/hackathon#10]
## Quais os critérios para escolha dos mentores?

Temos vagas para 10 times. Cada um dos 10 times vai mecher em frontend e backend. Alguns talvez mecham com mobile.

Então surgem as perguntas:

- Quantos mentores especializados em frontend, backend e mobile precisamos?
- Quantos anos de experiência precisam ter para serem mentores?
- Seria bom deixar alguém sendo responsável por atender os mentores em qualquer eventualidade, dúvida e etc.

Alguém quer add algo?

**Comment by khaosdoctor** [comment]
Acho que qualquer pessoa que é um mentor no CT pode se candidatar para mentorar, temos que ter pelo menos 2x a quantidade de times em quantidade de mentores, então acho que temos que ter 20 mentores no total, 10 para cada área de front ou back, assim sempre vamos garantir a disponibilidade

**Comment by danilosilvadev** [comment]
@khaosdoctor ah sim. E pessoas que não são mentores já do CT podem se candidatar? quais os critérios?

**Comment by khaosdoctor** [comment]
Acho que não, por mim não ela teria que ser um mentor já cadastrado no CT.
