### ISSUE TITLE
Cadastro de mentores

### ISSUE THREAD

**Issue by danilosilvadev** [training-center/hackathon#11]
## Critérios:

Essa issue será nosso cadastro de mentores. Para ser mentor do evento precisa primeiro estar cadastrado como mentor do CT nesse projeto [aqui](https://github.com/training-center/mentoria), e ter disponibilidade de pelo menos 2 períodos dos citados no campo **"horários"** e ir respondendo dúvidas, ajudando com consultoria mas nunca codando para os participantes.

## Datas importantes:

Data | Descrição
------------ | -------------
15/11/2017 | Início das inscrições para mentores.
Em breve | Início das inscrições dos participantes, em issues que criaremos.
31/01/2018 até 23:59 | Fim do período de inscrições dos mentores e participantes.
04/02/2018 | Fim do período de confirmação de pagamento da taxa de inscrição dos participantes.
09/02/2018 - 20hrs | Início do Hackacenter.
11/02/2018 - 20hrs | Fim do Hackacenter e início das avaliações dos mentores.
16/02/2018 - 20hrs | Fim da primeira fase e início da avaliação dos juízes.
19/02/2018 - 20hrs | Fim da segunda fase e anúncio do vencedor.

## Vagas:
Temos 20 vagas sendo estas:
10 Para frontend e 10 para backend.

*Se você for full stack serve como qualquer uma das vagas.*

## Horários:
1. Sexta 20:00 - 02:00 do domingo. (Mínimo 2 vagas de cada tipo).
2. Sábado 02:00 - 08:00. (Mínimo 1 vaga de cada tipo).
3. Sábado 08:00 - 14:00. (Mínimo de 4 vagas de cada tipo).
4. Sábado 14:00 - 20:00. (Mínimo de 4 vagas de cada tipo).
5. Sábado 20:00 - 02:00 do domingo. (Mínimo de 2 vagas de cada tipo).
6. Domingo 02:00 - 08:00. (Mínimo de 1 vaga de cada tipo).
7. Domingo 08:00 - 14:00. (Mínimo de 4 vagas de cada tipo).
8. Domingo 14:00 - 20:00. (Mínimo de 4 vagas de cada tipo).

## Mentores serão também juízes:

Após o concurso os mentores terão 5 dias para analisar todos os códigos e darem uma pontuação de 1 a 5 estrelas seguindo os critérios:

1. Clean code e escabilidade :
produto fluindo sem bugs (o projeto tem que funcionar)
código bem feito, escalável e manutenível

2. Ideia e como ela resolve o problema proposto
uma boa experiência de usuário
resolver bem o problema proposto (atendeu aos critérios informados antes da competição começar)

3. MVP(como a ideia será validada no mercado)

*Após isso os jurados terão 3 dias para analisar os 3 finalistas(que já vão ganhar alguma coisa cada) e escolher o vencedor. Os jurados só analisarão os vencedores na segunda fase. E os mentores só vão pontuar na primeira fase.*

## Inscrições:

Para se inscrever você pode acessar o link desse form [aqui](https://danilosilvaweb.typeform.com/to/Vh6Z51).

Após recebermos sua solicitação aguarde para receber um e-mail de confirmação da sua participação no projeto, e colocaremos seu GitHub aqui nos docs do concurso.

PS: No form pedimos o endereço para enviar um brinde pra você, essa parte não é obrigatória então caso não queira não precisa preencher.

**Dùvidas?**
Comente abaixo e responderemos assim que pudermos.

**Comment by hdamaich** [comment]
Meio difícil conseguir provisionar a disponibilidade sem uma data :(

**Comment by danilosilvadev** [comment]
@hdamaich boa. Vamos adicionar a data a essa issue para poder chamar os mentores

**Comment by khaosdoctor** [comment]
Mas tem a data ali não?

**Comment by danilosilvadev** [comment]
@khaosdoctor o comentário dele foi antes de eu add datas. rsrs

**Comment by khaosdoctor** [comment]
Opa vou apagar tudo então pra não nos perdermos kk

**Comment by danilosilvadev** [comment]
HACKATHON REDEFINIDO. NOVAS REGRAS E DIAS SERÃO POSTADAS EM BREVE.
