### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by danilosilvadev** [training-center/hackathon#2]
Escreva abaixo suas dúvidas/sugestões e a equipe responderá assim que puder.

**Comment by hdamaich** [comment]
O que será considerado como tempo de experiência?

**Comment by alinebastos** [comment]
Ótima pergunta, @hdamaich!

**Comment by khaosdoctor** [comment]
Ao meu ver, @hdamaich, tempo de experiência compreende todo o tempo que uma pessoa passou trabalhando na área correspondente ao Hackathon (no caso, desenvolvimento). Mas como profissional.

**Comment by tatisstiv** [comment]
![logo-hackathon](https://user-images.githubusercontent.com/20153969/32013920-59358e5e-b99b-11e7-90ae-ac480b9513aa.png)
No final vai ser esse logo mesmo, né?

**Comment by khaosdoctor** [comment]
Eu acho que a gente podia fazer alguma coisa já com o logo novo que o @adeonir fez @tatisstiv ai já podemos lançar com a brand nova. O @woliveiras tava pedindo pra esperar pra subir tudo junto

**Comment by tatisstiv** [comment]
To meio desatualizada quanto a isso, mas ok :)
