### ISSUE TITLE
Layout do site

### ISSUE THREAD

**Issue by danilosilvadev** [training-center/hackathon#3]
![web 1920 1](https://user-images.githubusercontent.com/15012584/29495479-899d0722-8596-11e7-8776-438d32fd49e8.png)

Então gostaria de opiniões se gostaram, se tem algo a acrescentar ou a tirar. Deixem ae abaixo se aprovam ou querem alterações.

**Comment by danilosilvadev** [comment]
**PS: O nome é só de exemplo, ainda não foi definido.**

**Comment by anony000** [comment]
Só o botão de "Inscreva-se" que tá meio grade hehe

**Comment by nicholasess** [comment]
O botão está bom, por que é o único CTA do site.

Nas listagens dos users, eu deixaria duas linhas de bio e as redes sociais lado a lado

**Comment by nicholasess** [comment]
Antes do jurados eu explicaria o que é o hackaton, pra fazer sentido ter aquela lista de jurados.
Abaixo dos jurados, colocaria o prêmio e seus benefícios, pra fazer sentido a lista da organização.

**Comment by nicholasess** [comment]
A primeira página está dando mais exposição a quem vai gerenciar, do que fazer o Dev se inscrever. Faltou outro CTA no final da página para reforçar a inscrição

**Comment by nicholasess** [comment]
Acredito que vai ajudar, se pesquisar sites dos Startup Weekend, eles têm o mesmo propósito.

**Comment by danilosilvadev** [comment]
1. O botão do header eu diminui levemente e add outro na sessão premiações, acho q ficou melhor.
2. Na listagem de jurados será q bio seria relevante pra quem acessa? o link do linkedin já tem a bio deles pra quem quiser conferir se eles tem gabarito(discutam ae).
3. Adicionei a sessão de "Premiações"
4. Explicar o q é hackaton, fiz logo abaixo do nome do evento agora.

![web 1920 1](https://user-images.githubusercontent.com/15012584/29495912-ae71bd06-859e-11e7-97f8-0ff659ee71c6.png)

**Comment by nicholasess** [comment]
Está muito branco e as cores não estão encaixando...
Pense as caixas como sessões, utilize alguns ícones para ilustrar é deixar menos texto na interface. Pega do font awesome

**Comment by danilosilvadev** [comment]
Ícones onde? E pôr cor onde? N entendo seu último comment.

**Comment by danilosilvadev** [comment]
Coloquei uma cor na parte das premiações e o menu com tarja preta fixo pra melhor navegação. Ficou melhor? pior?  tem algo a alterar?
![web 1920 1](https://user-images.githubusercontent.com/15012584/29496997-a30d76a0-85b5-11e7-95c0-5a9c08a14757.png)

**Comment by khaosdoctor** [comment]
E se fosse usado um modelo mais fullscreen? Tipo esse aqui: http://treekode.com/quercus/demo4/ ou esse aqui http://idenconsultoria.com.br/ (na questão do layout mesmo, esqueçam os vídeos e sliders). Ai a gente pode usar o menu para direcionar para essas sessões também como ancoras.

Acho que é legal usar alguma coisa mais quadrada mesmo ao invés de cantos arredondados.

**Comment by danilosilvadev** [comment]
Acho que fullscreen poderia dificultar um pouco na navegação pq ae obrigaria a pessoa a clicar nos botões para navegação em vez de rolar pq rolar levaria muito tempo. Sobre as âncoras já estava pensando em usar isso. O foco principal devem ser os textos e a navegação, não o design.

**Comment by khaosdoctor** [comment]
Mas é a rolagem mesmo, normalmente

**Comment by danilosilvadev** [comment]
Então o q eu falei é q dificultaria, n q impossibilitaria. Se cada assunto leva uma página inteira tenho q rolar muito pra ir pras próximas sessões ou clicar nos botões. Sem ser fullscreen dá menos trabalho pra quem rola.

**Comment by nicholasess** [comment]
@danilosilvadev no topo:
tira a barra preta, adiciona overlay na imagem de fundo e coloca na esquerda e o menu com letras brancas a direita.
Na parte de premiação, os números estão bagunçados, deixa-os alinhados ao topo.
Tira o bottom dos CTA's, deixa o botao chapado e no momento click, voce adiciona uma transição suave. Além disso, o padding de top/bottom está pequeno, deixa uma area de respiro.
PS: o CTA do topo está diferente do premiação, é necessario seguir o padrão

**Comment by nicholasess** [comment]
O padding top de cada sessão está diferente, veja o espaçamento entre o inicio da sessão com o titulo.

**Comment by nicholasess** [comment]
o padding left dos jurados e organizadores está diferente também.

**Comment by danilosilvadev** [comment]
**Fiz as alterações. Vejam qual opção ficou melhor.**

## Opção 1:
![web 1920 1](https://user-images.githubusercontent.com/15012584/29497798-1a9f362c-85c5-11e7-9c70-34c616b24396.png)

## Opção 2:
![web 1920 1](https://user-images.githubusercontent.com/15012584/29497805-46a4e03c-85c5-11e7-985b-95862550c9f4.png)

**Comment by danilosilvadev** [comment]
Outra coisa, o menu vou deixar só as opções regras e dúvidas q redirecionam pros tópicos no github. _Home_ não precisa pois é só uma page, âncoras parecia interessante mas tem muitas sessões ae ia ficar um menu grande porém o conteúdo é pequeno então n vai precisar rolar muito pra chegar no bottom do site. Então deixar um menu misto com links das regras e a parte com âncoras me pareceu estranho e meio confuso pra usabilidade. Logo pensei que só os dois links essenciais no menu já parecem de bom tamanho.  
**Regras e dúvidas.**
Alguém discorda?

**Comment by hdamaich** [comment]
Sobre os links pareceu fazer setindo, realmente o conteúdo é pequeno para colocar algum tipo de navegação na pagina, mais facil deixar o usuário rolar.
Achei estranho a parte dos Jurados virem antes da premiação, normalmente o usuário esta mais interessado no premio, logo se essa parte estiver mais em cima, poderá chamar mais atenção, mas claro no design não da para ter 100% de noção onde está o fold da pagina. 
Os background pretos estão meio fortes demais, parecem estar quebrando o design, quem sabe usar um preto (menos preto), ou então outra cor do logo do Training Center.
O botão inscreva-se de baixo não tem contrate com o background, acho que ele deveria ser de outra cor.

**Comment by khaosdoctor** [comment]
No comentário das opções, eu prefiro a 2 com o botão branco ao invés da mesma cor do fundo, acho que dá uma diferença mais fácil de ver.

**Comment by danilosilvadev** [comment]
Reduzi o contraste preto, coloquei as premiações logo depois do header e o background vermelho só nas sessões com foto pra equilibrar as cores do site com branco(pra n ficar uma área única colorida e uma toda branca). Agora só tem 2 botões no menu e tá mais simples. Galera vcs aprovam? podemos fechar a issue?

![web 1920 1](https://user-images.githubusercontent.com/15012584/29521146-a3a1bdc4-865a-11e7-9574-5628e1bb6cbd.png)

**Comment by khaosdoctor** [comment]
Eu até que gostei desse

**Comment by danilosilvadev** [comment]
Vou esperar até amanhã meio-dia pra opinarem mais e ae fecho a issue pra começar o desenvolvimento.

**Comment by ericmadureira** [comment]
Não manjo de design mas gostei dessa opção, pra mim ta aprovado! Sugestão: que tal mais um link "Conheça o Training Center"? Só pra garantir que mais gente conhecerá a comunidade por trás da hackathon.

**Comment by danilosilvadev** [comment]
Ok, layout aprovado. Vou fechar a issue.
