### ISSUE TITLE
Organização

### ISSUE THREAD

**Issue by woliveiras** [training-center/hackathon#6]
A nossa primeira edição está sendo organizada e para isso precisaremos de um time composto por:

Bancada organizadora: 3 homens e 3 mulheres
Bancada avaliadora: 2 homens e 2 mulheres
Time de pessoas que irão apadrinhar ou mentorar as equipes no dia do evento

Nessa issue aceitaremos as pessoas que desejam ajudar.

Se você quiser ajudar o evento acontecer de alguma maneira, comente aqui para que adicionemos você ao time.

**Comment by woliveiras** [comment]
Já temos:

Bancada organizadora:

* @danilosilvadev - Desenvolvedor do site
* @khaosdoctor - Coordenação
* @anony000 - Inserir função
* @tatisstiv - Marketing
* @anasanch - Inserir função
* @sabatiny - Inserir função

Bancada avaliadora:

* @khaosdoctor 
* @lflimeira 

Mentoria/Apadrinhamento: 

* @woliveiras
* @alinebastos

**Comment by anony000** [comment]
Opá! Conheço um carinha que gostaria de participar.

**Comment by khaosdoctor** [comment]
Manda ai @anony000 o/

**Comment by anony000** [comment]
Estou dentro para ajudar no que puder o projeto.

**Comment by khaosdoctor** [comment]
> Estou dentro para ajudar no que puder o projeto.

Cara eu juro que não tinha pego a piada haha Bora ajudar a gente! o/

**Comment by anony000** [comment]
Haha com certeza, do que precisam? Estou disposto a fazer o site do projeto.

**Comment by woliveiras** [comment]
O @danilosilvadev está cuidando do site, @anony000 

Vocês podem trocar ideia para se ajudarem ein. :+1:

**Comment by khaosdoctor** [comment]
Dá uma olhada no #3 lá @anony000 :D

**Comment by woliveiras** [comment]
Qual seu Telegram, @anony000?

**Comment by anony000** [comment]
@woliveiras Tenho não :/

**Comment by woliveiras** [comment]
Aaaaaaa, diacho!

**Comment by danilosilvadev** [comment]
Geral preenche esse typeform pra eu colocar no site suas info pfvr, assim que puderem.
https://danilosilvaweb.typeform.com/to/xOcaA2

**Comment by khaosdoctor** [comment]
@anony000 @sabatiny @anasanch Vocês podem responder esse form por favor? 😄

**Comment by woliveiras** [comment]
Galera, atualizei ali pra remover meu nome de produção.

Acho que produção poderia ficar como Training Center, não com meu nome.

Por que a realização mesmo é do grupo. Vocês que estão fazendo acontecer! :metal:
