### ISSUE TITLE
Cargos

### ISSUE THREAD

**Issue by danilosilvadev** [training-center/hackathon#8]
Aqui vamos discutir os cargos e atribuições destes.

# Serviços:

**Desenvolvimento**: responsável por desenvolver o site do projeto, sendo este responsivo(terminado).
**Divulgação**: responsável por divulgar e compartilhar links, notícias e etc sobre o hackathon em grupos do facebook, tags do twitter, fóruns, chats e outros lugares. Escrever posts e artigos que direcionem a divulgação do hackathon.
**Marketing**: responsável por bolar as estratégias, imagens de divulgação, vídeos chamada, parcerias com podcasters, youtubers e etc. O objetivo é aumentar ao máximo o alcance do projeto.
**Documentação**: responsável por criar as estruturas do projeto. Criar os arquivos .md e bolar regras, editar e organizar. Os docs precisam ser curtos, objetivos, claros e simples.
**Tesouraria**: responsável por arrecadar o dinheiro, documentar os recebimentos, autorizar participantes e administrar a utilização dele nos prêmios.

E ae alguém tem mais alguma ideia de outro serviço necessário? e qual o serviço que vc quer fazer? querem alterar algo? comentem as ideias abaixo.

**Comment by khaosdoctor** [comment]
Tem também o de organização e mentoria, jurados e etc

**Comment by danilosilvadev** [comment]
@khaosdoctor essa issue é só pros organizadores e suas funções.

**Comment by luan0ap** [comment]
**Divulgação** o/

**Comment by tatisstiv** [comment]
**Marketing** :)

**Comment by danilosilvadev** [comment]
A minha ideia pra vcs dois é essa:

Ok. Então o @luan0ap e a @tatisstiv vão trabalhar em conjunto. Vcs precisam se comunicar entre si pra organizar como vai ser. A @tatisstiv é a responsável por decidir o que o @luan0ap vai compartilhar, divulgar e etc. Porém tanto o @luan0ap pode dar umas ideias, dicas ou mesmo ajudar a editar algum material pra @tatisstiv quanto ela pode compartilhar na sua rede social, ou em outros sites um link ou material publicitário sobre o concurso. Mas lembrando que as decisões sobre a estratégia cabem @tatisstiv  mas a criação/divulgação delas pode ser feita pelos dois. 

Se puder @tatisstiv marque um meeting com o @luan0ap  no Skype ou em algum chat e ae crie um txt/doc ou mesmo criar uma issue aqui no repo com as ideias da estratégia do marketing que vcs tiverem pra apresentarem no nosso grupinho dos slack ae a gente tbm vai poder opinar e tals.

São importantes: 

- Alcance(como atingirá o máximo de pessoas?).
- Nicho(qual estratégia para q se direcione e converse especificamente com a comunidade de devs).
- Engajamento(qual a dinâmica de P.R. vcs vão usar?).
- Ferramentas(ex: divulgação no facebook, twitter, youtube etc), precisará de dinheiro? se sim quanto e como será arrecadado esse fundo? se não precisa de temers o que substituirá o dinheiro?

Outras ideias? algo que poderia ser diferente ou melhor? podem comentar a vontade.

**Comment by lflimeira** [comment]
Posso ajudar com a **Documentação**

**Comment by khaosdoctor** [comment]
Fico na *organização* e *bancada avaliadora* junto com o @lflimeira

**Comment by alinebastos** [comment]
Agora pode atuar em duas funções?
@khaosdoctor

**Comment by danilosilvadev** [comment]
@khaosdoctor

**Comment by tatisstiv** [comment]
@luan0ap me manda informações de contato tua pra gente marcar uma meeting, pode ser por aqui ou pelo meu e-mail: tati.s.stiv@gmail.com

**Comment by khaosdoctor** [comment]
Eu estava só como direcionador na coordenação ali, @alinebastos mas depois de uma conversa decidimos que o @danilosilvadev seria o mais indicado para ficar na organização já que ele está mais engajado nessa demanda. Ai eu e o @woliveiras vamos ficar provendo suporte com alguma coisa que ele precise e etc porque já estávamos no início do projeto.

Então minha função fica só na **bancada avaliadora** 😄

**Comment by luan0ap** [comment]
@tatisstiv Vou entrar em contato por email.
