### ISSUE TITLE
Estrutura da escolha dos vencedores

### ISSUE THREAD

**Issue by danilosilvadev** [training-center/hackathon#9]
# Sugestão da estrutura da competição:

### 1. Mentores serem os juízes:

Nessa ideia aqui todos os mentores serão juízes e os vencedores serão escolhidos por voto destes.

**Prós:** O maior benefício é que a escolha será mais justa e coerente já que virá de muitas pessoas que olharam o código e participaram do processo mentorando.
**Contras:** Os times precisam estar em pé de igualdade, então nenhum deles pode ter mais mentores que outro. Isso cai em duas possibilidades: 

1. Os mentores em todos os projetos: Precisarão olhar todos os códigos para julgar o melhor num rodízio de mentores e isso pode ser prejudicial porque os eles teriam que passar por muitos projetos diferentes com demandas que às vezes não sabem ajudar. Por exemplo, mentor frontend num projeto com demanda backend.

2. Mentores padrinhos/madrinhas: Esse aqui parece mais interessante pois os mentores podem ter um limite/meta de times para ajudar. Por exemplo: Mentora Ana que sabe frontend vai ser madrinha de 5 times e ae na hora do voto só vai poder votar em um fazendo assim mais justo. Já os times só vão poder ter 2 ou 3 mentores. Tipo: Ana do frontend, e o Clóvis do backend são mentores/padrinhos da chave vermelha que conta com 5 times. Deu pra entender? iríamos dividir por chaves que nem na copa tem os times de futebol. Cada chave teria 5 times, e o mentor não é padrinho do time e sim da chave(que podem ser cores). Ae ele vai analisar e ser justo. Os vencedores das chaves então apresentam o MVP para os juízes finais e conseguimos os vencedores(Nesse cenário os juízes finais analisam apenas os vencedores das chaves que acredito ser mais realista do que analisarem tds os times já q isso seria bem mais complicado e demorado, a ideia é dar o resultado no máximo 2 horas depois do fim da competição).

*PS: O número total de vagas para o hackathon tem haver com o número total de mentores disponíveis pros dias. Então não é ilimitado onde pode ter tipo 1000 coders. Isso acredito que não prejudique pois como é o primeiro não acho que terá mais de 100 participantes.*

*PS2: Seria interessante um número ímpar de juízes finais. Para a decisão não empacar.*

**Comment by khaosdoctor** [comment]
Eu concordo com o 1 mas não com o 2... Na minha opinião o negócio tem que ser assim:

Teremos um _pool_ de mentores, que vão ser as pessoas que querem ajudar esse _pool_ vai ficar em todos os canais de times, então teremos todos os mentores em todos os canais de forma que eles podem ajudar cada time individualmente, mas não podem dar dicas, apenas resolver problemas.

No final do evento, todos os mentores do _pool_ vão olhar o código e dar uma nota para este código, mas eles vão precisa justificar essa nota _"Dei a nota 8.5 porque faltou X coisa"_. Depois disso a bancada avaliadora olha o projeto como um todo (o MVP final mesmo, usabilidade e etc) e dá a sua própria nota e ai fazemos uma média ponderada (podemos dividir a questão de notas em várias categorias para ficar mais justo).

Não acho que vão existir taaaantas equipes que sobrecarreguem os mentores, mas podemos limitar o número de times

**Comment by danilosilvadev** [comment]
Ok. A maioria realmente está preferindo que todos analisem tudo, pq está sendo considerado que terá poucos times no evento. Foi citado até para pôr um limite de times. Qual é o limite? e quanto tempo os mentores/juízes vão ter para analisar todos os códigos?

Ah sim, e o que eu tinha sugerido era +- tipo isso(caso alguém não tenha entendido):

![intelig34](https://user-images.githubusercontent.com/15012584/32169525-9d18c426-bd4f-11e7-9bcd-34441b90501f.jpg)

**Comment by danilosilvadev** [comment]
O decidido foi:

 Limite de 10 times, ou seja, 50 programadores. E uma semana pra analisar. Sendo que o concurso será avaliado em duas fazes. A primeira é de 5 dias onde os mentores vão pontuar os projetos de 1 a 5 estrelas nos requisitos: 

1. Clean code e escabilidade :
produto fluindo sem bugs (o projeto tem que funcionar)
código bem feito, escalável e manutenível

2. Ideia e como ela resolve o problema proposto
uma boa experiência de usuário
resolver bem o problema proposto (atendeu aos critérios informados antes da competição começar)

3. MVP(como a ideia será validada no mercado)

Após isso os jurados terão 3 dias para analisar os 3 finalistas(que já vão ganhar alguma coisa cada) e escolher o vencedor. Os jurados só analisarão os vencedores na segunda fase. E os mentores só vão pontuar na primeira fase.

*Nesse cenário não haverá voto popular, como antes tinha se pensado de ter.*

Se ninguém tiver nada contra vamos fechar essa issue e alterar os docs do concurso.
